print("A Pythonic Ode\n")
print("In the land of code, where logic reigns,")
print("Python whispers in soft refrains.")
print("With indents clear and syntax bright,")
print("It guides us through the darkest night.\n")
print("No semicolons to end the line,")
print("Simplicity is Python's sign.")
print("From lists to loops, from strings to sets,")
print("It handles data with no regrets.\n")
print("A language built with grace and power,")
print("For every need, for every hour.")
print("So here we write, with joy and glee,")
print("In Python's world, forever free.")
